### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by BeckerFrank** [jonlil/vagrant-puppet-4-seed#1]
I download your example and got the following error

Bringing machine 'lb01' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The host path of the shared folder is missing: files

Is there something that I must configure?

In your zip file I can not found a folder "files". What is the content? do I need this?

**Comment by jonlil** [comment]
Hi, Thanks for the report.

The reason the folder doesn't exists is because i forgot to add it to the repository :)
solved by this 15a43ec3ec6745d6981a3f2c667633cd5af79d9f

One usage example of this is a way to handle files you want on your servers etc..

``` puppet
file { "/etc/somefile.conf":
   ensure => present,
   source => "puppet:///files/somefile.conf"
}
```
