### ISSUE TITLE
next error during install

### ISSUE THREAD

**Issue by BeckerFrank** [jonlil/vagrant-puppet-4-seed#2]
Now I have the following error.

Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::keepalived for lb01.speedport_w_724v_typ_a_05011603_00_007 at /tmp/vagrant-puppet/environments/production/manifests/base/loadbalancer.pp:7:5 on node lb01.speedport_w_724v_typ_a_05011603_00_007

How can I solve this?

**Comment by jonlil** [comment]
This error occurs because the keepalived package is not installed. I have forgot to add docs about 
https://github.com/rodjek/librarian-puppet

Either you get started with librarian-puppet or you just start to define your own nodes

**Comment by jonlil** [comment]
closed by 3dd44435d18a0fdf513496c5005d7e3b4965ba31
